CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	pass VARCHAR(100) NOT NULL
);

CREATE TABLE trips (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	lenght DOUBLE NOT NULL,
	user_id INT UNSIGNED NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE points (
	trip_id INT UNSIGNED NOT NULL,
	ord INT UNSIGNED NOT NULL,
	x FLOAT NOT NULL,
	y FLOAT NOT NULL,
	FOREIGN KEY (trip_id) REFERENCES trips (id),
	PRIMARY KEY (trip_id,ord)
);

